### ISSUE TITLE
Complaining `*sha1 is deprecated!`

### ISSUE THREAD

**Issue by ickc** [niksy/homebrew-pljoska#2]
Attached is the warning I received from cask:

``` bash
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/entizeta.rb:6:in `<class:Entizeta>'
Please report this to the niksy/pljoska tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/entizeta.rb:6:in `<class:Entizeta>'
Please report this to the niksy/pljoska tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/entizeta.rb:6:in `<class:Entizeta>'
Please report this to the niksy/pljoska tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/flegma.rb:6:in `<class:Flegma>'
Please report this to the niksy/pljoska tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/flegma.rb:6:in `<class:Flegma>'
Please report this to the niksy/pljoska tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/flegma.rb:6:in `<class:Flegma>'
Please report this to the niksy/pljoska tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/setfileicon.rb:7:in `<class:Setfileicon>'
Please report this to the niksy/pljoska tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/setfileicon.rb:7:in `<class:Setfileicon>'
Please report this to the niksy/pljoska tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Homebrew/Library/Taps/niksy/homebrew-pljoska/Formula/setfileicon.rb:7:in `<class:Setfileicon>'
Please report this to the niksy/pljoska tap!
```

**Comment by niksy** [comment]
@ickc can you check now?

**Comment by ickc** [comment]
The error is gone.

Actually I was using the Microsoft's font, and I realized it doesn't have sha256 checksum there: https://github.com/niksy/homebrew-pljoska/blob/master/Casks/font-microsoft-cleartype-family.rb

And then brew is complaining about another thing: `Warning: Calling Hbc::DSL#license is deprecated!`

**Comment by niksy** [comment]
@ickc this is another error and will be handled with #3.
